### ISSUE TITLE
KCV Crashes with update KB3132372

### ISSUE THREAD

**Issue by Iksapalif** [gakada/KanColleViewer#12]
On Windows 10 64bit, when update KB3132372 is installed, KCV will crash once the game is loaded. Removing said update would temporarily fix the issue. Apparently it's a security patch to fix bugs in the Internet Explorer's built-in flash player.

Will the next KCV update fix this or I just have to disable the update forever? Thanks.

**Comment by gakada** [comment]
This is https://github.com/Grabacr07/KanColleViewer/issues/176

It's known to [break](http://community.skype.com/t5/Windows-desktop-client/Skype-7-17-crash-on-startup/m-p/4242576) apps like Skype and [claimed](https://www.reddit.com/r/Windows10/comments/3z2qm9/microsoft_rolled_out_a_patch_kb3132372_to_plug/) to affect a lot more.

https://support.microsoft.com/en-us/kb/3132372

> We are aware of limited application crashes that occur after this security update is installed on Windows 10. 

> Microsoft is researching this problem with Adobe and will post more information in this article when the information becomes available.

For now you can hold onto this update and wait until situation is resolved.

**Comment by Iksapalif** [comment]
Oh, OK, thanks. I guess I'll just disable the update until Microsoft fixed it. Closing this issue now since it's solved.
