### ISSUE TITLE
4/1 Update Breaking KCV

### ISSUE THREAD

**Issue by martirsadota** [gakada/KanColleViewer#17]
Not sure what's happening, but whenever I log in to KC using KCV, the game loads, but KCV doesn't detect this (i.e., you're still stuck with the *Information* / *Browser* / *Window* tabs).

My hypothesis (I never looked at the code) is that KCV detects a game instance by listening for a `kcsapi/api_get_member/basic` API call. After the 4/1 update this call doesn't appear at all during game start (though I've seen it appear elsewhere), being replaced by a `kcsapi/api_get_member/require_info`.

**Comment by HaiUIT** [comment]
The API was changed, This issue will be fix soon

http://kancolle.wikia.com/wiki/Recent_Updates

**Comment by martirsadota** [comment]
Thanks for the fixes as usual.
