### ISSUE TITLE
Crashes with the CodeA plugin

### ISSUE THREAD

**Issue by Spasdl** [gakada/KanColleViewer#2]
Works fine with yuyuvn's latest version though.

**Comment by gakada** [comment]
This is how [develop](https://github.com/yuyuvn/KanColleViewer/commits/develop) is (r557 is from [master](https://github.com/yuyuvn/KanColleViewer/commits/master)). I will see if I can merge necessary commits from the [upstream](https://github.com/Grabacr07/KanColleViewer/commits/develop).

**Comment by gakada** [comment]
Should work in r558 now (it's also included in it).

**Comment by Spasdl** [comment]
Thanks a lot for the fix.
