### ISSUE TITLE
No information is being shown

### ISSUE THREAD

**Issue by Nukekip** [gakada/KanColleViewer#20]
I have this problems since this morning. I don't know why this happens and I already tried re-downloading the viewer but nothing changes :( Basically, almost no information is loading except for repairs.

![a8932dffafb896bc71808d18fdddca69](https://cloud.githubusercontent.com/assets/18700170/14851829/bd913b5e-0c82-11e6-88e7-938e4c7d1fe1.png)

**Comment by gakada** [comment]
Try to re-download to and launch from a different directory (so there is no Logs and BattleInfo txt files), try to disable all plugins before launching (delete/move Plugins directory). Also, https://github.com/gakada/KanColleViewer/issues/18#issuecomment-209402387 (clear appdata files, try to bisect the fork/version with problems).

**Comment by gakada** [comment]
Also, https://github.com/gakada/KanColleViewer#my-fleets-and-expeditions-dont-showupdate.

**Comment by Nukekip** [comment]
Thanks, it works again!
