### ISSUE TITLE
Shortcut in Start Menu crashes

### ISSUE THREAD

**Issue by sunbeams001** [gakada/KanColleViewer#23]
The KCV program will create a shortcut in "Start Menu\Programs" dir after running each time.
But it can not run properly, may here is a bad setting of property "Start in" ?

---
![image](https://cloud.githubusercontent.com/assets/3478170/14976380/c1cda134-113d-11e6-8ce3-687dd9b97f13.png)

**Comment by gakada** [comment]
Try to set "Start in" then (see [here](https://github.com/Yuubari/KanColleViewer/wiki/Frequently-Asked-Questions)).

**Comment by sunbeams001** [comment]
@gakada 
Thanks to your reply, but there are still some problems
1.The shortcut in "\Start Menu\Programs" folder but not "User Pinned\TaskBar" folder
2.I have tried to add the "start in" property, and it can works. But after running the KCV one time, the "start in" property just gone and it crashes again. I think the KCV force create a "wrong" shortcut when it runs.

**Comment by gakada** [comment]
Ok, I can reproduce \Start Menu\Programs shortcut renewal (with empty "Start in" field), but still can't reproduce the crash (starting from r559 working directory isn't used anymore, so empty "Start in" shouldn't have any effect, except maybe for some plugins). I will fix [InstallShortcut](https://github.com/gakada/KanColleViewer/blob/master/Plugins/WindowsNotifier/Windows8Notifier.cs) by setting the working directory. For now you can try to set "Start in" property and then read-only attribute for this shortcut (so KCV can't override it), or create another one (should have correct working directory and won't be updated by KCV, if you want a shortcut in \Start Menu\Programs, you can also hide the default one).

**Comment by sunbeams001** [comment]
You are right, I am using some local cache [plugin](https://github.com/Gizeta/KanColleCacher), and it just cause the crash.
