### ISSUE TITLE
Show equipment in reinforcement expansion?

### ISSUE THREAD

**Issue by c933103** [gakada/KanColleViewer#3]
Just saw a post promoting this version of KCV but noted its non-support of reinforcement expansion as a major drawback.

**Comment by gakada** [comment]
Yeah, this is certainly planned for next Event/pre-event release (I don't use them personally just yet).

**Comment by c933103** [comment]
I'd recommend release that now as there're numerous people who would use
the feature outside event.
2015/10/24 16:07 "gakada" <notifications@github.com>:

**Comment by gakada** [comment]
Is in [r560](https://github.com/gakada/KanColleViewer/releases/tag/v3.8.2r560) now.
