### ISSUE TITLE
KanColleViewer v3.8.2r560 did not start

### ISSUE THREAD

**Issue by HaiUIT** [gakada/KanColleViewer#6]
Your previous realease (v3.8.2r559) work fine on my laptop. But v3.8.2r560 did not start, when i run it, nothing happen, i check task manager but no KCV icon here. When i try to delete it, OS tell me that KCV is open in system.

**Comment by c933103** [comment]
I just close my KCV, unzip the kcv onto the original kcv, file, and then run the file and things work normally.

**Comment by c933103** [comment]
I just close my KCV, unzip the kcv onto the original kcv, file, and then run the file and things work normally.

**Comment by gakada** [comment]
I haven't changed anything related to startup, so it should work identical to r559 (you can also have multiple instances running, so it *should* start even if you didn't close another KCV).

What you can try: check if there is anything in processes in task manager (not just applications), reboot if anything, remove or backup settings in %APPDATA%\grabacr.net\KanColleViewer\, have it extracted to a folder with good permissions (e.g. not Program Files, but somewhere under your home directory), run it from there (it can give a security warning on a first run). Basically run it from a clean state, then it should start (and write `error.log` on critical errors).

**Comment by HaiUIT** [comment]
I copy KCV folder to my C:\ (my OS installed here) and run with administrator privileges, after 1-2 minutes, KCV work, then I close it and run again without administrator privileges, it starts quickly. Then I come back to the KCV folder in D:\ and run, still not work. Maybe i have to put it in C:\ from now (run the KCV in D:\ with administrator privileges  didn't work)

**Comment by gakada** [comment]
Maybe this is [cold startup](https://msdn.microsoft.com/library/cc656914(v=vs.100).aspx), depending on the system it can take some time (20s for me).

**Comment by HaiUIT** [comment]
After serveral time starting KCV in C:\ , i try to run KCV in D:\ and it work fine, maybe this problem is caused by cold startup as you say.
