### ISSUE TITLE
The CodeA doesn't work

### ISSUE THREAD

**Issue by samsonvodich** [gakada/KanColleViewer#9]
The codeA to help count quest Bw1-4 seems doesn't work.

**Comment by gakada** [comment]
Can you describe what exactly doesn't work? It generally works for me still, though it miscount things sometimes.

Also, it is third party plugin from (here)[https://github.com/smdhz/CodeA], I only did translations and didn't updated it, since it is for 4.x now.

**Comment by samsonvodich** [comment]
Oh nevermind, it's my mistake. I did the quest but in the event so it didn't count ' 3 '. Then i went to World 2-2 2-3, it worked normally. 
So sorry
